/** Lista padrão de opcionais/acessórios para cadastro e anúncio. */
export const ACESSORIOS_VEICULO_PADRAO = [
  'Ar-condicionado',
  'Direção hidráulica / elétrica',
  'Vidros elétricos',
  'Trava elétrica',
  'Airbag',
  'Freios ABS',
  'Alarme',
  'Som / multimídia',
  'Bluetooth / USB',
  'Câmera de ré',
  'Sensor de estacionamento',
  'Bancos de couro',
  'Rodas de liga leve',
  'Teto solar',
  'Piloto automático',
  'Faróis de neblina',
  'Retrovisores elétricos',
  'Computador de bordo',
  'Kit multimídia / Android Auto / CarPlay',
  'IPVA pago',
  'Licenciamento em dia',
  'Único dono',
  'Manual e chave reserva',
  'Revisões em dia',
] as const
